package com.locaobra.enums;

public enum Departamento {
    LOGISTICA_E_ALMOXARIFADO, // ENTREGADOR, CONFERENTE
    MANUTENCAO_E_PATIO, // TECNICO_MANUTENCAO, FAXINEIRO
    COMERCIAL_E_ATENDIMENTO, // CONSULTOR_LOCACAO, ANALISTA_CREDENCIAMENTO
    FINANCEIRO, // ANALISTA_FINANCEIRO
    OPERACOES, // GERENTE_OPERACOES
    RECURSOS_HUMANOS, // RH
    ESTOQUE,
    MANUTENCAO
}
